### ISSUE TITLE
Is this env available on Windows?

### ISSUE THREAD

**Issue by Henry658** [nctu-eva-lab/3DV-2022#6]
I tried to setup env by the command as:
conda env create --file requirements.yml
but some error happened
![image](https://user-images.githubusercontent.com/39232811/173137371-b712adea-5aef-4889-8c12-7ca1d66ac84a.png)
and I had alreadly google for it, but still didn't find out the way to slove it.

this command I tried on ubuntu on VM is working. but VM doesn't not support GPU.
I think without GPU, our project will not working well and consume(waste) a lot of time.

I also try to install dual-boot ubuntu and windows11.
[](https://www.youtube.com/watch?v=Z0T3uiCoEpA)
but in this moment, ubuntu can't detect my installed windows11.
and also installed GRUB bootloader fail, and that was fatal error.

So, my problem is that, is this project possible work on windows system?

**Comment by CharlesChiuGit** [comment]
VM doesn't support GPU, don't use VM for ML projects.
Dual-boot system is a good idea, but I assume you are new to this; hence got some setting wrong.
WSL2 + docker is another great way to do linux things in windows, since WSL2 has gpu supports now. Here another [ref](https://docs.nvidia.com/cuda/wsl-user-guide/index.html).
Never tested it on pure windows system. But since Anconda can be installed on windows, I assume it's doable.

And for your error, I think you're not in conda env. Please check again.

**Comment by CharlesChiuGit** [comment]
Also, you are asking a very vague problem, please specify:
1. What did you do before having this issue?
2. What had you tried to fix this issue?
TAs are not psychics.

Next time don't use screenshots, use code blocks to show your error messages.

**Comment by Henry658** [comment]
Thanks for your reply.

And wsl2 is a nice suggestion.

I successfully used wsl2 with vsconde extension to build my environment.

It can work now.

thank a lot
